sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0

notifications:
  email:
    - brian.altenhofel@vmdoh.com
  irc:
    - "irc.freenode.org#vmdoh"

env:
  - DRUPAL_VERSION=8.0.0-rc1

before_install:
  - composer self-update
  - wget http://ftp.drupal.org/files/projects/drupal-${DRUPAL_VERSION}.tar.gz
  - tar -zxf drupal-${DRUPAL_VERSION}.tar.gz
  - mv drupal-${DRUPAL_VERSION} ../build
  - cd ../build
  - cp ../openstack_queues/tests/travis.composer.json composer.json

install:
  - cp -R ../openstack_queues ./modules/openstack_queues
  - composer update -n --prefer-source --lock

script:
  - ./vendor/bin/phpunit -c core/phpunit.xml.dist --group openstack_queues --coverage-clover=./coverage.clover --verbose --debug

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.clover
