<?php

/**
 * @file
 * Contains basic functions for Marconi
 */

/**
 * Ensure that php-opencloud library is loaded.
 *
 * @return bool
 *   Returns TRUE if the library is loaded.
 */
function marconi_loaded() {
  $loaded = &drupal_static(__FUNCTION__);
  if (!isset($loaded)) {
    // Try loading via Composer Manager.
    if (!class_exists('\OpenCloud\OpenStack' && module_exists('composer_manager'))) {
      require_once DRUPAL_ROOT . '/sites/all/vendor/autoload.php';
      $loaded = class_exists('\OpenCloud\OpenStack');
    }
  }

  return $loaded;
}

/**
 * Get queue parameters.
 *
 * @param string $name
 *   The name of the queue.
 *
 * @return array
 *   An array of parameters for this queue.
 */
function marconi_get_queue_options($name) {
  $options = &drupal_static(__FUNCTION__);
  if (!isset($options[$name])) {
    $options[$name] = variable_get('marconi_queue' . $name, array());

    $defaults = variable_get('marconi_default_queue', array());
    $options[$name] += $defaults;
  }

  return $options[$name];
}
