openstack_queues.settings.*:
  type: config_object
  label: Openstack Queue configuration
  mapping:
    client_id:
      type: string
      label: 'UUID to identify the client.'
    auth_url:
      type: string
      label: 'The Openstack Identity service URL to use.'
    credentials:
      type: mapping
      mapping:
        username:
          type: string
        apiKey:
          type: string
    region:
      type: string
      label: 'The Openstack Region for the service.'
    prefix:
      type: string
      label: 'A prefix used to namespace queues within the service. (Optional, but recommended.)'